# $Id$

Description:

This is a test for UNKNOWN exceptions raised by the server.  There are
two places where this example tests for UNKNOWN exceptions: (a)
UNKNOWN exception raised in an upcall and (b) UNKNOWN exception raised
while a servant is being cleaned up after deactivation.  The number of
outstanding requests in the POA are checked after each unit of work
performed by the server.  The assumption is that if the number of
outstanding requests are correct, then the server correctly handled
the UNKNOWN exceptions.

Expected output:

A successful run is one without any asserts.  

The server should say:

- test_i::normal_method() called

- test_i::unknown_exception_in_method() called
  Unknown exception being generated: should be propagated to the client

- test_i::unknown_exception_during_deactivation() called
  Unknown exception being generated: should be gobbled up by the POA


And the client should say:

CORBA::UNKNOWN was thrown by the server during test::unknown_exception_in_method()
        This is expected behavior
